version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-phi4
    ports:
      - "11434:11434"
    volumes:
      - ollama-models-cache:/root/.ollama
      - ./entrypoint-simple.sh:/entrypoint.sh:ro
      - ./ollama_models:/shared:rw
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_DOWNLOAD_TIMEOUT=7200
      - OLLAMA_RETRY_DELAY=30
      - OLLAMA_MAX_RETRIES=100
      - HTTP_TIMEOUT=7200
      - DOWNLOAD_CHUNK_SIZE=1024
      - OLLAMA_MAX_QUEUE=1
      - OLLAMA_DOWNLOAD_RETRIES=50
      - OLLAMA_CONCURRENT_REQUESTS=1
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 4G
          cpus: '2'
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      disable: true

volumes:
  ollama-models-cache:
    driver: local

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"